defaults:
  - data: home_credit
  - preprocess: numeric_only
  - model: mlp
  - infer_params: default
  - _self_

paths:
  data_dir: data
  artifacts_dir: artifacts

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
