defaults:
  - data: home_credit
  - preprocess: numeric_only
  - model: mlp
  - infer_params: default
  - _self_

paths:
  data_dir: data
  artifacts_dir: artifacts

hf_urls:
  application_train: "https://huggingface.co/datasets/d-chibukhchian/credit-default-risk-scoring/resolve/main/application_train.csv?download=1"
  application_test: "https://huggingface.co/datasets/d-chibukhchian/credit-default-risk-scoring/resolve/main/application_test.csv?download=1"
