defaults:
  - data: home_credit
  - preprocess: numeric_only
  - model: baseline_perceptron
  - trainer: default
  - _self_

seed: 42

paths:
  data_dir: data
  artifacts_dir: artifacts

split:
  train_size: 0.70
  val_size: 0.15
  test_size: 0.15
  random_state: ${seed}

hf_urls:
  application_train: "https://huggingface.co/datasets/d-chibukhchian/credit-default-risk-scoring/resolve/main/application_train.csv?download=1"
  application_test: "https://huggingface.co/datasets/d-chibukhchian/credit-default-risk-scoring/resolve/main/application_test.csv?download=1"
